In [2]:
import numpy as np
print(np.__version__)


1.26.4


In [2]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros((5,3)).shape

(5, 3)

In [6]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
  np.zeros((5,3)).ndim


2

In [9]:
k = np.array([[5,3,4,6],[35,80,65,71]])
k.shape
type(k)

numpy.ndarray

In [16]:
np.arange(1,5)

array([1, 2, 3, 4])

In [4]:
g = np.arange(18)
g

g.reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [7]:
g.shape = (3,6)
g

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [8]:
g[1,3] = 100
g

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8, 100,  10,  11],
       [ 12,  13,  14,  15,  16,  17]])

In [15]:
k = np.array([[35,-80,65,71]])
k<50

array([[ True,  True, False, False]])

In [18]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([10,20,30]).reshape(-1,1)
np.matmul(A,B)

array([[140],
       [320]])

In [19]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
f = np.array([1,2,3]).reshape(-1,1)
f

array([[1],
       [2],
       [3]])

In [21]:
I.dot(f)

array([[1.],
       [2.],
       [3.]])